### ISSUE TITLE
Resolution of the output

### ISSUE THREAD

**Issue by VenturaHighway** [redplc/node-red-contrib-redplc-rpi-mcp342x#1]
Hello,

with the input signal of 2048 mV, the output value of node 2048 does not matter whether you set 12, 14, 16, 18 bits. The accuracy is therefore always 12 bits, regardless of which mode is selected. According to the data sheet, the output signal should be 131071 at 18bit resolution and an input of 2.048V. 

Thank you very much.

Best regards
Sven

**Comment by redplc** [comment]
Hi Sven,
the reference voltage of mcp34x is always 2048mV regardless of the resolution.
If you select 12bit (11bit + sign) one bit represents 1mV (2048/2048).
On 18bit (17bit + sign) one bit represents  0.156mV (2048/13107).
I rescale the value to mV and round the value after decimalpoint.
This looks, that the value is always same for all resolution, but 18bit measure more accurate.
But 18bit takes more time to convert.
In most cases is 12 or 14 bit resolution is sufficient.
Sorry for the behavior of this node.

**Comment by VenturaHighway** [comment]
Hello,

this is a very good node. I would like to transfer the output of a 30 kW photovoltaic system which is available as 0-10V to node red. therefore my question with the accuracy. It is okay like this. Thank you for the node
